### ISSUE TITLE
set up checklist / overview .md files for topics & exercises

### ISSUE THREAD

**Issue by 7yl4r** [ioos/bio_mobilization_workshop#1]
I want to create `.md` files that give an overview & relevant links for the topics and exercises listed in [the agenda](https://docs.google.com/document/d/1wlEkVAUvC7IoaokCypnGWKZ3nZWMoQtKLpIaNfXrALY/edit?usp=sharing).

**Comment by MathewBiddle** [comment]
#2 might be relevant first?

**Comment by MathewBiddle** [comment]
@7yl4r take a look at [the site](https://ioos.github.io/ocean_sciences_bio_workshop_2021/index.html) (hosted out of the [gh-pages branch](https://github.com/ioos/ocean_sciences_bio_workshop_2021/tree/gh-pages))

We can update the [episodes markdown files](https://github.com/ioos/ocean_sciences_bio_workshop_2021/tree/gh-pages/_episodes) to include the info you're thinking of. As right now they only have the outline from the agenda we discussed yesterday.

**Comment by 7yl4r** [comment]
The carpentries template resolved this even better than I was imagining. Thanks Matt!
