### ISSUE TITLE
Update schedule for 2024

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#100]
- [x] decide on schedule
- [x] update schedule.html for website

https://github.com/ioos/bio_mobilization_workshop/blob/a821ee3b8936ce8ff385ccf29f28a6c73ff1a504/_includes/custom-schedule.html#L1

**Comment by MathewBiddle** [comment]
Everyone alright with the [schedule](https://ioos.github.io/bio_mobilization_workshop/#schedule) for this year?

**Comment by jdpye** [comment]
Breakout room slide would be good!

**Comment by timvdstap** [comment]
Suggested a few edits to the schedule: https://github.com/ioos/bio_mobilization_workshop/pull/121

**Comment by timvdstap** [comment]
I'm thinking that hyperlinking Animal Telemetry might be confusing to people, they might think it directs them to the specific breakout room? Should we remove the hyperlink?

**Comment by MathewBiddle** [comment]
[last year](https://github.com/ioos/bio_mobilization_workshop/blob/a4c03c5744b94d767ed524bbb3cb7d2f8d54d080/_includes/custom-schedule.html#L66) we didn't hyperlink to the eDNA page from the workshop agenda.

I vote for removing the hyperlink but keeping the text.

**Comment by timvdstap** [comment]
- [ ] TODO: Add 16:30 timeslot on both days to get people back into the main room: Day 1 - Recap of the day, looking forward to day 2, and OBIS Node Managers can do a quick hello and describe their role. Day 2 - recap of day 2, continuining the conversation, get show of hands to see who will participate on day 3.
