### ISSUE TITLE
Add something about how to continue the conversation after the workshop

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#11]
We should include a page(?) on where to continue having the discussions after the workshop.

Need to think about where to put it?

**Comment by 7yl4r** [comment]
Thinking on this is what motivated me to open https://github.com/ioos/bio_data_guide/issues/94.

The Marine Bio Data Workgroup repo should be the page for continued discussions via gh issues and monthly meeting attendance.

**Comment by MathewBiddle** [comment]
agreed. We should include something on the workshop site to point folks there.

**Comment by 7yl4r** [comment]
Let's add a final page which includes:

* [ ] instruction on how to upload your data, + a README, and upload code to the bio_data_guide repo `datasets` section.
* [ ] survey on how the workshop went

**Comment by MathewBiddle** [comment]
related #16

**Comment by MathewBiddle** [comment]
Add this to the [Discussion page](https://github.com/ioos/bio_mobilization_workshop/edit/gh-pages/_extras/discuss.md)?

![image](https://user-images.githubusercontent.com/8480023/154357451-f7cbecbb-c82a-46ab-bc3b-ceaf2dbe5786.png)

Or, just make a new episode page?

**Comment by albenson-usgs** [comment]
I vote for a new episode page but it's only a slight preference. I think it will be easier for participants to find. Not that the Extras is hard to find but it takes an extra step to look for it. Obviously we would point people there but if it's on the first page people won't miss it.

>  rm links to my surveys that everyone hated. 🙃

We like the idea just want to use a different method 🙂

**Comment by MathewBiddle** [comment]
This is done here: https://ioos.github.io/bio_mobilization_workshop/07-post-workshop/index.html

Thanks @7yl4r!
