### ISSUE TITLE
Fix the schedule table

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#125]
something isn't rendering right with the html in https://github.com/ioos/bio_mobilization_workshop/blob/gh-pages/_includes/custom-schedule.html

![image](https://github.com/ioos/bio_mobilization_workshop/assets/8480023/9c6067e2-5417-4c8e-96b8-c10c6269a7df)

I will look at this shortly.

**Comment by timvdstap** [comment]
It might be from me adding <td></td> to those lines?

**Comment by MathewBiddle** [comment]
Yeah, looking at this now.
