### ISSUE TITLE
Send out certificates to workshop participants

### ISSUE THREAD

**Issue by timvdstap** [ioos/bio_mobilization_workshop#135]

**Comment by timvdstap** [comment]
@laurabrenskelle Could you be able to redo the certificate for `Maripa Tomasino`? The name on the certificate should read 'Maria Paola Tomasino'. Thanks!

**Comment by laurabrenskelle** [comment]
@timvdstap Sure thing. Sending it your way now.

**Comment by timvdstap** [comment]
Awesome, all certificates have been sent! I'll keep this issue open in case any participants want a pdf version.

**Comment by MathewBiddle** [comment]
Please update https://github.com/ioos/bio_mobilization_workshop/tree/gh-pages/certificate with anything we learned from this year's approach. I think there was an issue with one of the icons?

**Comment by timvdstap** [comment]
@laurabrenskelle I believe only Kathryn McKenzie was wondering whether she could have her certificate in PDF. Would you be able to do that? I think we can close this issue after :) TIA!

**Comment by laurabrenskelle** [comment]
Sure, @timvdstap. I will send that in a bit.

@MathewBiddle where should I document things learned/to improve upon for the certificates for next year?
