### ISSUE TITLE
pre and post-workshop survey

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#16]
OBIS has some?

**Comment by MathewBiddle** [comment]
carpentries has some

**Comment by MathewBiddle** [comment]
https://docs.carpentries.org/topic_folders/assessment/assessment.html#post-workshop-survey

**Comment by cperaltab** [comment]
> OBIS has some?

Hi! As far as I know OBIS doesn't have a specific/standardized pre-post surveys for courses/workshops. In general, most of OBIS courses are delivered through the Ocean Teacher Global Academy and they are the one who send the surveys to the participants. I could try to get one example for us. However it would be very helpful to create a survey that OBIS could adopt for future "internal" workshops (not the ones delivered by the OTGA).

**Comment by 7yl4r** [comment]
Survey draft [here](https://docs.google.com/forms/d/e/1FAIpQLSdiNqJA8sLcZLKsTvuglO1M6_ew2HtR8pVE2Jxlui94kAHcQA/viewform?usp=sf_link).

I want to remove some of the carpentries questions. Maybe we can talk through that briefly in the run through today.

**Comment by MathewBiddle** [comment]
I'd like to leave this open until we add a link to the survey here:
https://github.com/ioos/bio_mobilization_workshop/blob/gh-pages/_includes/custom-schedule.html
