### ISSUE TITLE
Add extras page

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#22]
- [ ] GBIF DwC Vadlidator
- [ ] Search NERC

**Comment by MathewBiddle** [comment]
@albenson-usgs should we do one page? Name it `Extras`?

Or, two pages:
- GBIF
- NERC

**Comment by MathewBiddle** [comment]
Like this: ![image](https://user-images.githubusercontent.com/8480023/157277351-8d15ffdd-c0ef-44f2-8c89-50c2121788d1.png)

**Comment by MathewBiddle** [comment]
See https://ioos.github.io/bio_mobilization_workshop/helpful-tutorials/

Not complete, but the page is started.

**Comment by albenson-usgs** [comment]
Yes that looks good to me!
