### ISSUE TITLE
Things to think about for next time

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#24]
- pre-workshop survey: https://docs.google.com/forms/d/e/1FAIpQLSeLsNrcwfU2EGtObf_E97juI55LZGR2Fc8VsPpTSpRmXG7ufA/viewform?usp=sf_link

**Comment by albenson-usgs** [comment]
https://github.com/ioos/bio_mobilization_workshop/issues/10

**Comment by MathewBiddle** [comment]
If we continue to get folks to provide some boilerplate info on the dataset they plan to work on. Maybe we can make breakout rooms topical based on data types, instead of lesson pages. Eg. passive acoustic, edna, survey, trawl, etc.

Just thinking of other ways the breakout rooms could be more engaging...

**Comment by albenson-usgs** [comment]
I would have both so people can go work with people that have the same data but go get help when they need it from an instructor. I think that might help break up the breakout rooms more effectively. I would not have an instructor in the topical rooms as I don't think we will have someone with the specialized knowledge to handle all questions that might arise about a particular sampling method.

**Comment by MathewBiddle** [comment]
Create a google group mailing list for the SMBD WG? 

https://groups.google.com/

**Comment by albenson-usgs** [comment]
Create better descriptions of the breakout rooms so people know what room to go to ask their question.

**Comment by albenson-usgs** [comment]
Should we make the workshop longer (a full week?) to build in GTKY/ networking time?

**Comment by sformel-usgs** [comment]
full eDNA video and episode

**Comment by timvdstap** [comment]
Resource relationship extension (Tim)
Nice icebreaker idea from Naomi - have people add pin for where they’re located, and perhaps a pin for the general area of their dataset?
