### ISSUE TITLE
Fix section 4 title on main page

### ISSUE THREAD

**Issue by albenson-usgs** [ioos/bio_mobilization_workshop#26]
<img width="359" alt="Capture" src="https://user-images.githubusercontent.com/7586150/157769059-b55dc3f4-ee48-4e0c-86a7-60cbc30c40dd.PNG">

Section 4 should reflect the title that we have updated it to: "Metadata, QA/QC, and publishing". I tried to edit this myself on the main page but I think it's actually pulling from the URLs? Or at least I couldn't figure out where the text was to update it.

**Comment by MathewBiddle** [comment]
![image](https://user-images.githubusercontent.com/8480023/157879573-5afe8a8b-f99d-4ae7-9b4e-eea56c9a01c4.png)
