### ISSUE TITLE
Standardize I/you language in the POST survey

### ISSUE THREAD

**Issue by 7yl4r** [ioos/bio_mobilization_workshop#27]
from Carolina Peralta:
> Some questions are placed in first personal pronoun (I) and others are in second person (you). I suggest to standardize (Did this workshop help me move past the blockers I identified?; How comfortable are you with aligning data to Darwin Core?) Maybe use all questions with "I" personal pronoun?

Survey form is editable in gforms. Let me know if you need edit access granted.

**Comment by MathewBiddle** [comment]
@7yl4r, we're you able to fix this? Otherwise I can work through it before we end today.

**Comment by MathewBiddle** [comment]
Form: https://docs.google.com/forms/d/e/1FAIpQLSdiNqJA8sLcZLKsTvuglO1M6_ew2HtR8pVE2Jxlui94kAHcQA/viewform?usp=sf_link

**Comment by 7yl4r** [comment]
I modified a question or two but I feel it is most clear in its current format. The 1-5 scale questions make sense as "I agree" statements but other questions (like the NPM and "more feedback") feel more natural as "you" questions.

I defer to your judgement, @MathewBiddle , but I am comfortable with closing this.

**Comment by MathewBiddle** [comment]
Looks good to me. Thanks!
