### ISSUE TITLE
Make `gh-pages` the default branch

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#29]
So, it looks like we didn't use the `main` branch as we were thinking (documented in [CONTRIBUTING.md](https://github.com/ioos/bio_mobilization_workshop/blob/main/CONTRIBUTING.md)).

I'm thinking we should make the `gh-pages` branch the default for this repository. It will make contributing easier and allow us to see more details on how the repo might be used (in the insights section). Other than the binder [environment file](https://github.com/ioos/bio_mobilization_workshop/blob/main/.binder/environment.yml) (which didn't work all that great to begin with - and it could be copied to `gh-pages`) there is no other purpose for `main`. 

I can make `gh-pages` the default, but should we delete `main`?

**Comment by MathewBiddle** [comment]
default branch changed to `gh-pages`.

**Comment by 7yl4r** [comment]
I don't think we need to retain the `main` branch, but the README content from `main` isn't on the `gh-pages` branch. We should copy it over to gh-pages and then delete.
