### ISSUE TITLE
update CITATION

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#30]
Before TDWG we need to update the citation file. Maybe push to zenodo and get a DOI too?

**Comment by 7yl4r** [comment]
Should we reference to this one:

```
[Open Source Workshop to Mobilize Marine Biodiversity Data](https://scholar.google.com/scholar?oi=bibs&cluster=13673515263635619875&btnI=1&hl=en)
A Benson, M Biddle, T Murray, J Pye, T van der Stap - Biodiversity Information Science and Standards, 2022
[All 4 versions](https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=13673515263635619875)
``` 

or something else?

**Comment by MathewBiddle** [comment]
reference - yes! I think [CITATION.cff](https://citation-file-format.github.io/#/what-is-a-citation-cff-file) allows referencing to related things?

**Comment by MathewBiddle** [comment]
https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#referencing-other-work

**Comment by MathewBiddle** [comment]
Well, this didn't happen... Still something I would like to do, however. I'll add Jon and Tylar.

**Comment by MathewBiddle** [comment]
Citation will be:
```
Biddle, M., Benson, A., van der Stap, T., Pye, J., & Murray, T. (2022). Marine data mobilization workshop (Version 1.0) [Computer software]. https://github.com/ioos/bio_mobilization_workshop
```
