### ISSUE TITLE
Create a release, tag, and mint DOI

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#35]
I'd like to have a DOI for this repo. 

TODO:

- [x] Create a release
- [x] tag said release
- [x] mint doi through Zenodo
- [x] update citation.cff

**Comment by timvdstap** [comment]
Tim van der Stap - 0000-0002-0053-0795

**Comment by MathewBiddle** [comment]
done in:
* https://github.com/ioos/bio_mobilization_workshop/commit/8a69ecca6e30c9d4b0e06802badbce96ca58ac8b
* https://github.com/ioos/bio_mobilization_workshop/commit/24588b4dd251649994156599ead40bfbeeb1963f
