### ISSUE TITLE
Create separate pages for different events?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#36]
Say we were to hold this workshop again, how can we host the different workshops materials so they are available online?

I think Oceanhackweek did some neat tricks to make this happen?

cc: @ocefpaf

**Comment by ocefpaf** [comment]
> I think Oceanhackweek did some neat tricks to make this happen?

To be honest I'm not familiar with the current OHW page. @abkfenris re-wrote the whole thing.
However, any versioning scheme would do. My recommendation is to move the old page to a `URL/year_of_the_event` and create the new one with links to the old one.

**Comment by 7yl4r** [comment]
The best options I am imagining:

1. create a branch `2022` to keep the older version code & use main for the latest version
2. fork this to a new repo named bio_mobilization_workshop_2022

The only reason for (2) instead of (1) is to keep the older github pages website up. Which.. do we even want that?

**Comment by abkfenris** [comment]
To keep past OceanHackWeek docs around, we made sure that each event lived under it's own path, then we didn't clean up the branch on each deploy, so we slowly accrete events over time.

https://github.com/oceanhackweek/oceanhackweek.github.io/blob/17719174695e9983b26bbc02ce5777cd5b1e5a66/.github/workflows/deploy-docs.yml#L22-L29

**Comment by 7yl4r** [comment]
our build process is quite a bit different.

https://github.com/ioos/bio_mobilization_workshop/blob/41455eb42c381c296febc72b442b226a90a59fc6/.github/workflows/website.yml#L93-L119

maybe we should switch over to JamesIves/github-pages-deploy-action?

**Comment by jdpye** [comment]
I like the idea of having a history of what was taught at each year's workshop in a subfolder. Is it that simple/ does that work well enough, to make a tag for the last year's workshop gh-pages branch, then hive it off into a subfolder of the newest iteration and let gh-pages continue to evolve?

**Comment by jackVanish** [comment]
Hi all, Bruce D. from OTN here (one of Jon's henchmen). We tackled a problem similar to this with our own workshop series, and where we landed was to fork new repositories for new workshop content, and leave the old repositories and their github pages extant but unmaintained. We do like Jon says and maintain a list of old workshop content that people can access, here: https://ocean-tracking-network.github.io/otn-workshop-base/12-other-curriculums/index.html. 

Our basic practice is to fork from our base workshop (the one we linked above) and then edit the content as needed to fit the workshop we want to deliver on its own gh-pages site, and that's worked pretty well for us. While in theory I like the idea of shunting old content off into subfolders and keeping everything in one site, in practice I don't think it's workable. To the best of my knowledge a lot of these Carpentries site setups rely on things being in the correct place so that they are rendered and linked properly. If we start putting things in other folders, we could end up scotching the render process for older content. 

While it does mean that you accrue repos as you go, it also means that you can leave them alone and not have to worry about them as you make your new content. That's the solution that's worked for us, anyway!

**Comment by MathewBiddle** [comment]
Thanks for all the input here. I am concerned with repo proliferation if we were to fork a 'base' workshop for each year. 

I think we need to sit down and really think about how much content will be changing between years. And if we need that content available for all iterations. If anything I think these workshops will either refine existing content or provide updated guidance, we wouldn't need to point back to 2022 guidance as 2023 should contain the same/updated info? 

I wonder if we could just keep this simple and do yearly tagged releases of the `gh-pages` branch? `gh-pages` will always be the most up-to-date (but could be in-development for the next year). Maybe farm off each year into it's own branch as @7yl4r describes?

**Comment by ocefpaf** [comment]
> Maybe farm off each year into it's own branch as @7yl4r describes?

tags and branches are different but with similar functionalities. IMO we should use tags to "freeze" a page for a certain year and develop the latest one on the "main" gh-pages. Older pages can be published on a `/year-of-the-event`. Keeping all pages in the same repo and under the same domain.

**Comment by MathewBiddle** [comment]
@ocefpaf I like that approach. 

But, can you explain?
> Older pages can be published on a `/year-of-the-event.`

I guess I don't understand how we would accomplish that, technically.

**Comment by albenson-usgs** [comment]
> The best options I am imagining:

create a branch 2022 to keep the older version code & use main for the latest version
fork this to a new repo named bio_mobilization_workshop_2022
The only reason for (2) instead of (1) is to keep the older github pages website up. Which.. do we even want that?

I am concerned about the question at the end of Tylar's suggestion. Yes we do want to keep the website up because we have been linking to it like in [this news post](https://obis.org/2022/04/12/biodatamob/) up on OBIS. If the website disappears that would be problematic in my mind? Unless we are going to have each new year of the workshop at this specific link (https://ioos.github.io/bio_mobilization_workshop/) and people could still get to the "curriculum"?

**Comment by MathewBiddle** [comment]
@albenson-usgs The way I read @7yl4r's comment is that we will always have a page at https://ioos.github.io/bio_mobilization_workshop/ which will be the most recent iteration of the workshop. The question is about if we want to make the previous year's material still available as a webpage?

In your example above, would it be problematic of that link to the curriculum went to the most recent materials? Or, do we need it to go to the materials for 2022 specifically?

**Comment by albenson-usgs** [comment]
> In your example above, would it be problematic of that link to the curriculum went to the most recent materials? Or, do we need it to go to the materials for 2022 specifically?

Good question. The blog post is specifically about the 2022 workshop so to me it is a bit strange to point to a curriculum that is for say 2025 but maybe I'm overthinking it. It just feels a little strange to do that here when in general we promote maintaining and ensuring accessibility to all versions of say data that's being publishing in a workshop like this. But it's probably fine and realistically not too many people are going to want to get to specifically the 2022 workshop website and if they really wanted to get to that content specifically they would be able to access it via GitHub.

**Comment by ocefpaf** [comment]
> But it's probably fine and realistically not too many people are going to want to get to specifically the 2022 workshop website and if they really wanted to get to that content specifically they would be able to access it via GitHub.

I agree with that assessment. Keeping old pages is only worth for  "googling" purposes. Anyone that knows how the workshop is organized will find whatever they need much faster on GH.

**Comment by MathewBiddle** [comment]
After re-reading the comments, I'm a little confused as to where we landed. I think it was decided to try and work the content into a structure documented by @ocefpaf above https://github.com/ioos/bio_mobilization_workshop/issues/36#issuecomment-1348867468. 

The PR I submitted does not do that. It changes the 2022 page to reflect new dates for 2023. But, does not keep 2022 as a persistent url.

If we do want to pursue keeping persistent urls for previous year's materials, we need to be cognizant of the comments by @jackVanish 
> To the best of my knowledge a lot of these Carpentries site setups rely on things being in the correct place so that they are rendered and linked properly. If we start putting things in other folders, we could end up scotching the render process for older content.

I was able to get the carpentries template to function and make it work for our needs, but this might be going beyond my ability. If anyone has specific guidance on how to do this, I would appreciate it. Otherwise it will be trial and error.

**Comment by 7yl4r** [comment]
I am sure there is a tooling out there to help with "archiving" of a site in this way, but I don't know of it.

**Comment by MathewBiddle** [comment]
I've started tinkering around with this and found https://github.com/jekyll/jekyll-archives which could be another pathway.

I've also been testing with [Jekyll collections](https://jekyllrb.com/docs/collections/) to create a `previous` collection which contains the lessons from a specific year. The benefit of this method is:
1. Simple to manage
2. Keeps everything built out of the same repo
3. don't need to fiddle with the GH-action.

However, this doesn't allow us to keep the home landing page for any previous workshops. I've tried adding the index.md to the specific directory, but the links still go to the root files (not the previous ones). I suppose we could start mucking around in the configuration to allow for these changes, but I'm not sure it's worth the time.  

Right now, we end up with an html directory of the specific lessons. I don't think that is very useful to folks. 
![image](https://user-images.githubusercontent.com/8480023/213565447-818e0f64-fef4-43bd-84d8-cec4d151632f.png)

I will push my changes to my fork so folks can take a look and see what they think.

**Comment by 7yl4r** [comment]
This may be a dumb idea, but: what if we switch away from github pages to another static hosting provider? [It looks like](https://github.com/orgs/community/discussions/21582) netlify and antora.org support sites published from branches, and worst case we can build out a custom deploy workflow in github actions. 

Branches and tags work so well for this within git that it seems like a shame to lose that.

**Comment by MathewBiddle** [comment]
Deployed a test site. Below is an example of how I've implemented collections:

This url would be the 'active' page (so where we'd be developing 2023 content)
https://mathewbiddle.github.io/bio_mobilization_workshop/05-break/index.html

Then, if you'd like to get to the previous year's material:
https://mathewbiddle.github.io/bio_mobilization_workshop/2022/05-break/index.html

This assumes someone **knows the url structure**.

I'll look around and see if there is a simple configuration we can add to say 'if the page is in this collection, change the urls to use [predefined] structure. That way we can at least have the pages link to the appropriate year's page.

Now that I look at it more, we are loosing the headers, navigation, etc. when reading in this collection. 😠

**Comment by 7yl4r** [comment]
[The way readthedocs handles versioning](https://docs.readthedocs.io/en/latest/versions.html#tags-and-branches) is the ideal behavior. From what I am finding the jekyll+carpentries tooling used here does not support that. Building this functionality would benefit the carpentries ecosystem in general so maybe we should take this conversation upstream to that community and see if there is interest.

There are a ton of ways to engage with the carpentries community [[ref](https://carpentries.org/community/)]. Unfortunately I think this fits best under "infrastructure" and that seems to be inactive.

**Comment by 7yl4r** [comment]
> [The way readthedocs handles versioning](https://docs.readthedocs.io/en/latest/versions.html#tags-and-branches) is the ideal behavior. From what I am finding the jekyll+carpentries tooling used here does not support that. Building this functionality would benefit the carpentries ecosystem in general so maybe we should take this conversation upstream to that community and see if there is interest.
> 
> There are a ton of ways to engage with the carpentries community [[ref](https://carpentries.org/community/)]. Unfortunately I think this fits best under "infrastructure" and that seems to be inactive.

Ha! Nevermind. Matt beat me to it: https://github.com/carpentries/workshop-template/issues/779

I am hopeful we will see some discussion there.

**Comment by MathewBiddle** [comment]
Just something to note. To see what has changed between different iterations. We can compare tags to branches. So, for example, to see the difference between the 2022 materials and what we're currently working on, you can browse to https://github.com/ioos/bio_mobilization_workshop/compare/2022...gh-pages to get a summary.

This has me wondering how badly we need previous years materials available on a webpage?

**Comment by 7yl4r** [comment]
> This has me wondering how badly we need previous years materials available on a webpage?

Honestly... I hadn't really thought hard on this. The only reason I would use the old webpages is if the newer page didn't capture something as well as the older one did, and hopefully that won't happen.

**Comment by MathewBiddle** [comment]
Decision - We have releases and tags and doi's and commit history to trace back previous year's materials. We will simply update the materials and not serve the 2022 website.

**Comment by 7yl4r** [comment]
:shipit:
