### ISSUE TITLE
outdated information on Darwin Core and Extension Schemas page

### ISSUE THREAD

**Issue by ymgan** [ioos/bio_mobilization_workshop#41]
Hi 

I am just scheming through the pages for the workshop and noticed some information that may have outdated. I don't know what the original information should be, so I could not submit a pull request for the [Darwin Core and Extension Schemas page](https://ioos.github.io/bio_mobilization_workshop/04-create-schema/index.html)

> Occurrence Core + extensions
> 
> Using the occurrence core plus [relevant extensions](https://tools.gbif.org/dwca-validator/extensions.do) means that you can capture more of the data that’s been recorded.

The link https://tools.gbif.org/dwca-validator/extensions.do now points to the new data validator login page, but not the extensions

---

In the occurrence extension table, row `basisOfRecord`: 

> Pick from these controlled vocabulary terms: [HumanObservation](http://rs.tdwg.org/dwc/terms/HumanObservation), [MachineObservation](http://rs.tdwg.org/dwc/terms/MachineObservation), [PreservedSpecimen](http://rs.tdwg.org/dwc/terms/PreservedSpecimen), [LivingSpecimen](http://rs.tdwg.org/dwc/terms/LivingSpecimen), [FossilSpecimen](http://rs.tdwg.org/dwc/terms/FossilSpecimen)

There are more vocabularies for `basisOfRecord` (e.g. MaterialSample)

**Comment by MathewBiddle** [comment]
@ymgan do you mind submitting a PR with your proposed changes?
