### ISSUE TITLE
Post workshop certification of attendance?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#45]
What happened to our discussions about a certification of sorts?

Can we create some PDF that we send folks after the workshop to say they attended? A certification of attendance...

**Comment by MathewBiddle** [comment]
Some blogs on how to create one in R, using LaTEX: https://www.andreashandel.com/posts/2020-10-15-customized-documents-with-rmarkdown/

**Comment by MathewBiddle** [comment]
This would probably require participants to add their names to a csv in this repo. That would be a neat idea, if folks were comfortable in doing so.

**Comment by albenson-usgs** [comment]
Good call. I think it's only documented in our notes and not as a ticket. We should figure out how to do this.

**Comment by MathewBiddle** [comment]
Since I don't have to rebuild the site, I am interested in spending some time working through this. The link above gives a good template to start with. Some things to consider:

- [ ] Where in the repo to start the participant csv
- [ ] Structure of csv
- [ ] Guidance to participants on how to update said csv
- [ ] Some checker to review csv for consistency
- [ ] What should the cert. look like
- [ ] Graphics to include in cert. (need to be licensed with cc-nc?)

**Comment by 7yl4r** [comment]
We might consider using Mozilla's OpenBadges standard via badgr.com. I haven't used it, but I believe it is free, and I am a fan of the OpenBadges philosophy developed by Mozilla.

**Comment by MathewBiddle** [comment]
@7yl4r I like the badgr idea but I'd like something more reproducible and contained in this repo. 

I guess one concern is folks could just run the script to generate the certification to fake their attendance. Hopefully we don't need to worry about that...

Maybe @sformel-usgs has some thoughts?

**Comment by sformel-usgs** [comment]
I've never used badgr, but after reading a little about it seems like there are some academic circles where it's heavily used, but not so many government agencies. @7yl4r does that seem right? I also think most folks would probably be content to list the workshop on their CV, and that few will need/want certificates.

That's kind of a long way of saying I think the github approach would be sufficient for our attendees needs.  And if someone goes through the trouble of faking their attendance, then I think we can cross that bridge when it happens.  TBH, that would be pretty flattering if attendance at our workshop was desirable enough to fake! 

But, I also don't feel very strongly about this, so if either of you do feel strongly, I'm happy to follow your lead.

**Comment by MathewBiddle** [comment]
copied the carpentries stuff into our repo. See https://github.com/ioos/bio_mobilization_workshop/tree/gh-pages/certificate

Need to think on the .svg file

**Comment by MathewBiddle** [comment]
images: https://www.phylopic.org/

![image](https://user-images.githubusercontent.com/8480023/230407668-0e0cf1cd-9cf1-443c-b1f3-20607ddd402f.png)

**Comment by jdpye** [comment]
I spent a few minutes trying to find a pacific-centric version of the globe logo. Does your comment there mean that you'd want to make it a taxa silhouette from phylopic.org ?

**Comment by MathewBiddle** [comment]
It's just an option. I was just jotting down different ideas. 

I don't have strong feelings as to what we should use for the image.

**Comment by jdpye** [comment]
All good, layoutwise i am learning a lot of things about embedding svg in svg that I didn't know before. The template part is relatively easy with the jinja2 version, just supply all the variables you'd want to supply, we roll through an attendee list with a python loop and we are happy there. Just looking at grabbing svgs and child svgs that will cover all the visual elements.

**Comment by MathewBiddle** [comment]
yup. Started work at https://github.com/MathewBiddle/bio_mobilization_workshop/blob/certificate/certificate/bin/make_certificate.py 

can probably use some cleanup, but the gist is there.
