### ISSUE TITLE
Review Metadata and Publishing page

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#52]
https://ioos.github.io/bio_mobilization_workshop/07-validation-and-publishing/index.html

**Comment by sformel-usgs** [comment]
Reviewed and approved

**Comment by MathewBiddle** [comment]
@laurabrenskelle and I took a look at this last week and think it looks good. The image on the page is different than what's in @sformel-usgs's recording. Is that worthy of a re-record?

@laurabrenskelle LMK what you think.

**Comment by MathewBiddle** [comment]
Decided recording is fine. Closing.
