### ISSUE TITLE
address build website GHA warnings

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#62]
I've seen some warning pop up that we should probably look at. I don't think it's a **requirement** to fix asap, per se.

https://github.com/ioos/bio_mobilization_workshop/actions/runs/4449218838

[build-website](https://github.com/ioos/bio_mobilization_workshop/actions/runs/4449218838/jobs/7813087410)
```
Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
```

[build-website](https://github.com/ioos/bio_mobilization_workshop/actions/runs/4449218838/jobs/7813087410#step:7:10)
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by 7yl4r** [comment]
I think these are resolved, but be on the lookout for weirdness.

* I am not 100% confident in the syntax I used in https://github.com/ioos/bio_mobilization_workshop/commit/ca0a890e00704eaeb99c8e599ce989fc05b25d6a# 
* I assumed there were no relevant "API" changes in the variables we used between setup-python@v2 vs setup-python@v4

**Comment by MathewBiddle** [comment]
Seems to be working alright - https://github.com/ioos/bio_mobilization_workshop/actions/runs/4449735025

at least no warnings and the page updates as expected 🤷
