### ISSUE TITLE
Speed up build time for webpage

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#77]
Build time takes a bit to publish site updates (~3 mins). We probably don't need all the RMarkdown stuff...

https://github.com/ioos/bio_mobilization_workshop/blob/6bb30392b6a5ba04dbcec5a0667bae5bb2c992f3/.github/workflows/website.yml#L44-L89

**Comment by 7yl4r** [comment]
There isn't any executable code, right? It is all just markdown rendering that is needed. Since we are using R to render I think we still need R around though.

**Comment by MathewBiddle** [comment]
> There isn't any executable code, right?

Correct, no executable code.

> Since we are using R to render I think we still need R around though.

That's where I wasn't sure. We render some static R code on the pages, but does that need a full R environment? The way I'm reading the action is that it looks for R markdown documents

https://github.com/ioos/bio_mobilization_workshop/blob/6bb30392b6a5ba04dbcec5a0667bae5bb2c992f3/.github/workflows/website.yml#L44-L47

which we don't have any:

https://github.com/ioos/bio_mobilization_workshop/tree/gh-pages/_episodes_rmd

Looking closer, there are `if` statements in the action which skip the `R` stuff if there aren't `.rmd` files. For example,
https://github.com/ioos/bio_mobilization_workshop/actions/runs/4757453050/jobs/8454289924#step:7:1


The big time sucks are:
* https://github.com/ioos/bio_mobilization_workshop/blob/a4c03c5744b94d767ed524bbb3cb7d2f8d54d080/.github/workflows/website.yml#L30-L32
* https://github.com/ioos/bio_mobilization_workshop/blob/a4c03c5744b94d767ed524bbb3cb7d2f8d54d080/.github/workflows/website.yml#L91-L92

**Comment by 7yl4r** [comment]
Those are (1) jekyll installation steps, (2) jekyll rendering steps.
They are essential for turning the md into html.

**Comment by MathewBiddle** [comment]
Not much we can do about it then. 🤷
