### ISSUE TITLE
Tag 2023 materials, mint doi, attach html pages as assets to release?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#78]
2023 is now complete. We should tag the website materials. I _think_ zenodo will automatically mint a new doi for a new version, but also provide a collection DOI for all versions ([link](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content)).

> Zenodo archives your repository and issues a new DOI each time you create a new GitHub [release](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases). Follow the steps at "[Managing releases in a repository](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository)" to create a new one.

For example,

* https://doi.org/10.5281/zenodo.7401979 - cite all versions
* https://doi.org/10.5281/zenodo.7401980 - cite just 2022

Also, I wonder if there is a way to add the `.html` files to the release. Just thinking in case jekyll disappears we wouldn't be able to rebuild the website again. If we drop the `.html`  files in as assets to the release, folks would be able to pull those up in a browser. Just not sure if those will be pulled over to the zenodo DOI package.

**Comment by MathewBiddle** [comment]
For the later piece, it might be too tricky to do. All the html files will reference local server address `http://127.0.0.1:4000` and need to be served via jekyll to link between everything. Having the standalone html files will be less than helpful. 

I tried to do it locally by building and serving the website with `bundle exec jekyll serve`. That created `_site/` with all the html for the page. However, when I terminate `bundle exec jekyll serve` the page no longer resolves. If I pull up the index.html file, it looks like the `.css` file doesn't read properly either and all the hyperlinks to lesson pages don't resolve to the correct place. 
![image](https://user-images.githubusercontent.com/8480023/233390946-e5a27663-610a-4d9b-ac35-3a24a39198fe.png)

So, after some sleuthing, I don't think it's worth figuring out how to make the standalone html useful.

But, I did find this if someone really wants to go down that road:
https://stackoverflow.com/questions/26778329/running-jekyll-generated-files-without-jekyll-local-server

Additionally, it looks like zenodo does not pull over release artifacts https://github.com/zenodo/zenodo/issues/1235

**Comment by MathewBiddle** [comment]
updated https://github.com/ioos/bio_mobilization_workshop/releases/edit/untagged-bc205b0defeb08eb2497

**Comment by 7yl4r** [comment]
I *think* github automatically creates a .zip archive of all files in the repo at the tagged release commit, so everything needed to create the html using jekyll will be there. The site won't be hosted anywhere, but we will be able to revisit that later if we want to.

**Comment by MathewBiddle** [comment]
Published new release! https://github.com/ioos/bio_mobilization_workshop/releases/tag/2023

https://doi.org/10.5281/zenodo.7401979 - cite all versions
https://doi.org/10.5281/zenodo.7401980 - cite just 2022
https://doi.org/10.5281/zenodo.7896606 - cite just 2023
