### ISSUE TITLE
Create dataset registration issues in this repo instead of bio_data_guide?

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#92]
I heard once or twice from attendees about confusion on the dataset registration issues. I think it might have been confusing why we had folks adding issues to `bio_data_guide` instead of this workshop repository. 

If I recall correctly, the reason we did that was to get folks involved in the SMBDWG and post their issues to the space we use for that working group. Which would more fluidly feed into ongoing activities, beyond the workshop.

After the last workshop, I'm wondering if it would be clearer for attendees to post their dataset description issues to this repository? 

At least if we created the issues here it would more tightly couple the datasets with the workshop. But, maybe that doesn't matter.

**Comment by albenson-usgs** [comment]
I didn't receive any comments like that so I'm guessing here but I doubt that the location of the repo was the issue. I'm going to guess that most participants weren't even really aware that there is a GitHub repo associated with the website. So it's probably less about what repo the GitHub issues were being entered in and more about that we asked them to create a GitHub issue at all. That's my guess.
