### ISSUE TITLE
Add elizabeth and steve to citation

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/bio_mobilization_workshop#94]
@EliLawrence and @sformel-usgs, can you share your orcid's? Let's get you added to the citation!

https://github.com/ioos/bio_mobilization_workshop/blob/1db214d0b0a759f87c709a482624851681d31568/CITATION.cff#L19-L34

**Comment by albenson-usgs** [comment]
When you have the updated citation can you pass it along to me so I can send the workshop write up to OBIS?

**Comment by MathewBiddle** [comment]
humm, so we have a conundrum. 

GitHub provides this citation based on the [CITATION.cff](https://github.com/ioos/bio_mobilization_workshop/blob/gh-pages/CITATION.cff) file.

> Biddle, M., Benson, A., van der Stap, T., Pye, J., Murray, T., Lawrence, E., & Formel, S. (2023). Marine data mobilization workshop (Version 2023) [Computer software]. https://doi.org/10.5281/zenodo.7401979

However, zenodo provides this citation (from the 2023 tag):
> Biddle, Mathew, Benson, Abby, van der Stap, Tim, Pye, Jonathan, & Murray, Tylar. (2023). Marine data mobilization workshop (Version 2023). Zenodo. https://doi.org/10.5281/zenodo.7896606

I'm looking into how we can update the zenodo record to include the additional authors.

**Comment by MathewBiddle** [comment]
Okay, I had to manually update the record. Zenodo now provides this citation:

> Biddle, Mathew, Benson, Abby, van der Stap, Tim, Pye, Jonathan, Murray, Tylar, Lawrence, Elizabeth, & Formel, Stephen. (2023). Marine data mobilization workshop (Version 2023). Zenodo. https://doi.org/10.5281/zenodo.7896606

**Comment by albenson-usgs** [comment]
Thank you!
